# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-27 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'classification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('pro_id', models.IntegerField(primary_key=True, serialize=False)),
                ('coloring', models.FloatField(blank=True, db_column='Coloring', null=True)),
                ('moisture', models.FloatField(blank=True, db_column='Moisture', null=True)),
                ('durability', models.FloatField(blank=True, db_column='Durability', null=True)),
                ('pushing_evenness', models.FloatField(blank=True, db_column='Pushing_evenness', null=True)),
                ('waterproof', models.FloatField(blank=True, db_column='Waterproof', null=True)),
                ('distinctness', models.FloatField(blank=True, db_column='Distinctness', null=True)),
                ('naturalness', models.FloatField(blank=True, db_column='Naturalness', null=True)),
                ('transparency', models.FloatField(blank=True, db_column='Transparency', null=True)),
                ('saturation', models.FloatField(blank=True, db_column='Saturation', null=True)),
                ('concealer', models.FloatField(blank=True, db_column='Concealer', null=True)),
                ('sticking', models.FloatField(blank=True, db_column='Sticking', null=True)),
                ('refreshing', models.FloatField(blank=True, db_column='Refreshing', null=True)),
            ],
            options={
                'db_table': 'effect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField()),
                ('pro_name', models.TextField(blank=True, null=True)),
                ('pro_time', models.CharField(blank=True, max_length=45, null=True)),
                ('pro_price', models.FloatField(blank=True, null=True)),
                ('pro_pic', models.TextField(blank=True, null=True)),
                ('pro_score', models.FloatField(blank=True, null=True)),
                ('pro_color', models.TextField(blank=True, null=True)),
                ('rgb', models.CharField(blank=True, db_column='RGB', max_length=45, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
