# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-27 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_products2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_id', models.IntegerField()),
                ('pro_name', models.TextField(blank=True, null=True)),
                ('pro_time', models.CharField(blank=True, max_length=45, null=True)),
                ('pro_price', models.FloatField(blank=True, null=True)),
                ('pro_pic', models.TextField(blank=True, null=True)),
                ('pro_score', models.FloatField(blank=True, null=True)),
                ('pro_color', models.TextField(blank=True, null=True)),
                ('rgb', models.CharField(blank=True, db_column='RGB', max_length=45, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
