# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-28 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_product_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='similarity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id_1', models.IntegerField()),
                ('product_id_2', models.IntegerField()),
                ('similar', models.FloatField(blank=True, null=True)),
                ('appearence', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
