# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-28 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_similarity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='similarity',
            new_name='Similarity_cos',
        ),
    ]
